
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build SecondtJob
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeploytJob

- stage: QADeploy
  dependsOn: DevDeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob

- stage: ProdDeploy
  dependsOn: DevDeploy
  dependsOn: QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeloyJob
