trigger:
- master

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - bash: echo "DO THE BUILD"
- stage: DevDeploy
  jobs:
    deployment: DevDeployJob
    environment: dev
    strategy:
      run0nce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: QADeploy
  jobs:
    deployment: DevDeployJob
    environment: QA
    strategy:
      run0nce:
        deploy:
          steps:
          - script: echo deploy to Dev
  
steps:
- script: echo Running on $(operatingSystem)!
  displayName: 'Run a one-line script'



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
